import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Dashboard from "@components/ui/dashboard";
import "./globals.css";
import Dashboard2 from "@/components/ui/dashboard2";
import UIProvider from "@/components/UIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <UIProvider>
          <div>
            <Dashboard />
          </div>
          {children}
        </UIProvider>
      </body>
    </html>
  );
}